# * Deep Learning Challenges  ✨🎄

# ---------------------------------------------------------------------------

## Problem Statement:

##  3.	Build a ANN classification model to predict breast cancer(malignant or benign )

## -----------------------------------------------------------------------------------

### Problem Objective:
### The main objective of data set is to predict whether a patient has breast cancer(malignant or benign ) using a simple ANN model

## -----------------------------------------------------------------------------------

In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv(r"G:\360digit\AI&DL\Assignments\5. Deep learning Challenges\breast_cancer.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [52]:
df = df.drop(["id", "Unnamed: 32"], axis=1)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Executing shutdown due to inactivity...


2021-09-03 14:38:00,397 - INFO     - Executing shutdown due to inactivity...


Executing shutdown...


2021-09-03 14:38:08,550 - INFO     - Executing shutdown...
C:\Users\Hp\anaconda3\envs\DL\lib\site-packages\dtale\app.py:397: UserWarning:

The 'environ['werkzeug.server.shutdown']' function is deprecated and will be removed in Werkzeug 2.1.



In [5]:
import dtale
dtale.show(df)

### Choosing X and y:

In [6]:
X = df.drop('diagnosis',axis = 1)
y = df['diagnosis']

### Scaling the data;

In [7]:
from sklearn.preprocessing import scale
X = scale(X)

In [8]:
X

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [9]:
y.unique()

array(['M', 'B'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
y = enc.fit_transform(y)

In [15]:
y[:50]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0])

### Train/Test data split

In [17]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=42)

In [18]:
Xtrain

array([[-0.10999635, -0.32105347, -0.15854246, ..., -0.82857392,
        -0.89100191, -0.76506065],
       [-0.2150816 , -0.67476767, -0.24174666, ..., -0.37801891,
        -1.37957166, -0.42480753],
       [ 0.15981713, -1.23559085,  0.25747857, ..., -0.05795583,
        -0.11932056,  0.45076239],
       ...,
       [ 0.04621146, -0.57470379, -0.06874782, ..., -1.23756033,
        -0.71628161, -1.26047806],
       [-0.04183295,  0.07687501, -0.03497186, ...,  1.03683652,
         0.45013821,  1.19444266],
       [-0.5530585 ,  0.28631105, -0.60751564, ..., -0.61357437,
        -0.33448538, -0.84042616]])

## Model:

In [45]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(40, input_dim = 30, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(1, activation='tanh'))

In [46]:
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
history = model.fit(Xtrain, ytrain, epochs=100, batch_size=20)

Epoch 1/100
20/20 [==============================] - 0s 2ms/step - loss: 2.2264 - accuracy: 0.7136
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 1.1973 - accuracy: 0.8467
Epoch 3/100
20/20 [==============================] - 0s 1ms/step - loss: 0.9655 - accuracy: 0.8869
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7937 - accuracy: 0.9070
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.7387 - accuracy: 0.9171
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6915 - accuracy: 0.9196
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5456 - accuracy: 0.9246
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.4581 - accuracy: 0.9322
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3794 - accuracy: 0.9397
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 0.3358 - accuracy: 0.9472
Epoch 11/

20/20 [==============================] - 0s 1ms/step - loss: 0.0850 - accuracy: 0.9950
Epoch 83/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0851 - accuracy: 0.9950
Epoch 84/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0846 - accuracy: 0.9950
Epoch 85/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0843 - accuracy: 0.9950
Epoch 86/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0842 - accuracy: 0.9950
Epoch 87/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0841 - accuracy: 0.9950
Epoch 88/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0839 - accuracy: 0.9950
Epoch 89/100
20/20 [==============================] - 0s 900us/step - loss: 0.0838 - accuracy: 0.9950
Epoch 90/100
20/20 [==============================] - 0s 1000us/step - loss: 0.0837 - accuracy: 0.9950
Epoch 91/100
20/20 [==============================] - 0s 1ms/step - loss: 0.0836 - accuracy: 0.9950
Epoch 92

### Prediction:

In [48]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(Xtest)
y_pred = np.argmax(y_pred, axis=1)
accuracy_score(ytest, y_pred)

0.631578947368421

### Evaluation:

    * Plotting Loss against  no of epochs

In [40]:
import matplotlib.pyplot as plt
plt.plot(history.history['loss'])
plt.xlabel('Epochs')
plt.ylabel('Loss')

Text(0, 0.5, 'Loss')